#https://trello.com/1/appKey/generate
#https://trello.com/1/connect?key=<appKey>&name=OpenShift&response_type=token&scope=read,write,account
#https://trello.com/1/connect?key=<appKey>&name=OpenShift&response_type=token&scope=read,write,account&expiration=never
---
:consumer_key: <consumer_key>
:consumer_secret: <consumer_secret>
:oauth_token: <oauth_token>
:oauth_token_secret: <oauth_secret>
:max_lists_per_board: 26
:default_product: product1
:other_products:
  - product2
  - product3
:teams:
  :team1:
    :boards:
      :team1_board1: <team1_board1_id>
      :team1_board2: <team1_board2_id>
  :team2:
    :boards:
      :team2_board: <team2_board_id>
:roadmap_id: <roadmap_id>
:public_roadmap_id: <public_roadmap_id>
:documentation_id: <documentation_board_id>
:docs_new_list_name: New
:organization_id: <organication short name>
:organization_name: <organization display name>
:roadmap_board_lists:
 - 'New'
 - 'Epic Backlog'
:sprint_length_in_weeks: 3
:sprint_start_day: monday
:sprint_end_day: friday
:logo: <logo url>
:archive_path: <archive path>
